spring:
  datasource:
    username: newroot
    password: root
    url: jdbc:mysql://localhost:3306/account
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 9000
  error:
    include-message: always
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/ 
customProperty:
  test: pekamwarpooja
management:
  endpoints:
    web:
      exposure:
        include: refresh, health
       
      
