server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/userdb5
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true  
  application:
    name: AUTH-SERVICE
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/ 
jwt:
  secret: mySecretKey
  expireMs: 120000
  refrEshexpireMs: 120000
